// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // Departments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class Department
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // name (length: 50)
        public int? Web { get; set; } // web
        public int? Checkstock { get; set; } // checkstock
        public string Stockstatusid { get; set; } // stockstatusid (length: 5)
        public string Description { get; set; } // description (length: 2147483647)
        public string Pictureext { get; set; } // pictureext (length: 3)
        public int? Browsestyle { get; set; } // browsestyle
        public int? Classlisting { get; set; } // classlisting
        public int? Numproducts { get; set; } // numproducts
        public int? Numproductsperrow { get; set; } // numproductsperrow
        public int? Showmanufacturer { get; set; } // showmanufacturer
        public string Coloralias { get; set; } // coloralias (length: 25)
        public string Sizealias { get; set; } // sizealias (length: 25)
        public string Subsizealias { get; set; } // subsizealias (length: 25)
        public int? Tnheight { get; set; } // tnheight
        public int? Tnwidth { get; set; } // tnwidth
        public string Fabricalias { get; set; } // fabricalias (length: 25)
        public string DeptTitleTag { get; set; } // dept_title_tag (length: 150)
        public string Flags { get; set; } // flags (length: 15)
        public string PersCode { get; set; } // pers_code (length: 15)
        public int? Dontshowdefprodpic { get; set; } // dontshowdefprodpic
        public int? Pagesbeforeafter { get; set; } // pagesbeforeafter
        public int? Paginationbottom { get; set; } // paginationbottom
        public int? Paginationtop { get; set; } // paginationtop
        public string Pricelabel { get; set; } // pricelabel (length: 30)
        public string CompareAtLabel { get; set; } // compare_at_label (length: 30)
        public string SaleRegpriceLabel { get; set; } // sale_regprice_label (length: 30)
        public string SalepriceLabel { get; set; } // saleprice_label (length: 30)
        public string StockstatusLabel { get; set; } // stockstatus_label (length: 30)
        public int Browsesortstyle { get; set; } // browsesortstyle
        public string Modelidalias { get; set; } // modelidalias (length: 25)
        public int? Productdetailstyle { get; set; } // productdetailstyle
        public decimal DefaultWeight { get; set; } // default_weight
        public string Manufactureralias { get; set; } // manufactureralias (length: 25)
        public int? Showfabric { get; set; } // showfabric
        public string Relateditemsalias { get; set; } // relateditemsalias (length: 75)
        public int? Relateditemsnumperrow { get; set; } // relateditemsnumperrow
        public int? Displaydepartmentimage { get; set; } // displaydepartmentimage
        public int? Displaycolorsavailable { get; set; } // displaycolorsavailable

        // Reverse navigation

        /// <summary>
        /// Child Classes where [Classes].[departmentId] point to this entity (FK_Departments_ToTable)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> Classes { get; set; } // Classes.FK_Departments_ToTable
        /// <summary>
        /// Child Products where [Products].[departmentId] point to this entity (FK_Departments_ToProdcut)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Products.FK_Departments_ToProdcut
        /// <summary>
        /// Child ReceiptLines where [ReceiptLine].[department] point to this entity (FK_Department_ToReceiptLine)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ReceiptLine> ReceiptLines { get; set; } // ReceiptLine.FK_Department_ToReceiptLine
        /// <summary>
        /// Child Skus where [Skus].[departmentId] point to this entity (FK_department_ToSkuu)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Sku> Skus { get; set; } // Skus.FK_department_ToSkuu
        /// <summary>
        /// Child SubClasses where [SubClasses].[departmentId] point to this entity (FK_Departments_ToSubClass)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SubClass> SubClasses { get; set; } // SubClasses.FK_Departments_ToSubClass

        public Department()
        {
            Dontshowdefprodpic = 0;
            Paginationbottom = 0;
            Paginationtop = 0;
            Browsesortstyle = 0;
            Productdetailstyle = 0;
            DefaultWeight = 1.00m;
            Showfabric = 0;
            Relateditemsnumperrow = 3;
            Displaydepartmentimage = 0;
            Displaycolorsavailable = 0;
            Classes = new System.Collections.Generic.List<Class>();
            Products = new System.Collections.Generic.List<Product>();
            ReceiptLines = new System.Collections.Generic.List<ReceiptLine>();
            Skus = new System.Collections.Generic.List<Sku>();
            SubClasses = new System.Collections.Generic.List<SubClass>();
        }
    }

}
// </auto-generated>
