// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // Departments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class DepartmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Department>
    {
        public DepartmentConfiguration()
            : this("dbo")
        {
        }

        public DepartmentConfiguration(string schema)
        {
            ToTable("Departments", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"name").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Web).HasColumnName(@"web").HasColumnType("int").IsOptional();
            Property(x => x.Checkstock).HasColumnName(@"checkstock").HasColumnType("int").IsOptional();
            Property(x => x.Stockstatusid).HasColumnName(@"stockstatusid").HasColumnType("nvarchar").IsOptional().HasMaxLength(5);
            Property(x => x.Description).HasColumnName(@"description").HasColumnType("text").IsOptional().IsUnicode(false).HasMaxLength(2147483647);
            Property(x => x.Pictureext).HasColumnName(@"pictureext").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(3);
            Property(x => x.Browsestyle).HasColumnName(@"browsestyle").HasColumnType("int").IsOptional();
            Property(x => x.Classlisting).HasColumnName(@"classlisting").HasColumnType("int").IsOptional();
            Property(x => x.Numproducts).HasColumnName(@"numproducts").HasColumnType("int").IsOptional();
            Property(x => x.Numproductsperrow).HasColumnName(@"numproductsperrow").HasColumnType("int").IsOptional();
            Property(x => x.Showmanufacturer).HasColumnName(@"showmanufacturer").HasColumnType("int").IsOptional();
            Property(x => x.Coloralias).HasColumnName(@"coloralias").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.Sizealias).HasColumnName(@"sizealias").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.Subsizealias).HasColumnName(@"subsizealias").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.Tnheight).HasColumnName(@"tnheight").HasColumnType("int").IsOptional();
            Property(x => x.Tnwidth).HasColumnName(@"tnwidth").HasColumnType("int").IsOptional();
            Property(x => x.Fabricalias).HasColumnName(@"fabricalias").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.DeptTitleTag).HasColumnName(@"dept_title_tag").HasColumnType("nvarchar").IsOptional().HasMaxLength(150);
            Property(x => x.Flags).HasColumnName(@"flags").HasColumnType("nvarchar").IsOptional().HasMaxLength(15);
            Property(x => x.PersCode).HasColumnName(@"pers_code").HasColumnType("nvarchar").IsOptional().HasMaxLength(15);
            Property(x => x.Dontshowdefprodpic).HasColumnName(@"dontshowdefprodpic").HasColumnType("int").IsOptional();
            Property(x => x.Pagesbeforeafter).HasColumnName(@"pagesbeforeafter").HasColumnType("int").IsOptional();
            Property(x => x.Paginationbottom).HasColumnName(@"paginationbottom").HasColumnType("int").IsOptional();
            Property(x => x.Paginationtop).HasColumnName(@"paginationtop").HasColumnType("int").IsOptional();
            Property(x => x.Pricelabel).HasColumnName(@"pricelabel").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.CompareAtLabel).HasColumnName(@"compare_at_label").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.SaleRegpriceLabel).HasColumnName(@"sale_regprice_label").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.SalepriceLabel).HasColumnName(@"saleprice_label").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.StockstatusLabel).HasColumnName(@"stockstatus_label").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.Browsesortstyle).HasColumnName(@"browsesortstyle").HasColumnType("int").IsRequired();
            Property(x => x.Modelidalias).HasColumnName(@"modelidalias").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.Productdetailstyle).HasColumnName(@"productdetailstyle").HasColumnType("int").IsOptional();
            Property(x => x.DefaultWeight).HasColumnName(@"default_weight").HasColumnType("decimal").IsRequired().HasPrecision(15,2);
            Property(x => x.Manufactureralias).HasColumnName(@"manufactureralias").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.Showfabric).HasColumnName(@"showfabric").HasColumnType("int").IsOptional();
            Property(x => x.Relateditemsalias).HasColumnName(@"relateditemsalias").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.Relateditemsnumperrow).HasColumnName(@"relateditemsnumperrow").HasColumnType("int").IsOptional();
            Property(x => x.Displaydepartmentimage).HasColumnName(@"displaydepartmentimage").HasColumnType("int").IsOptional();
            Property(x => x.Displaycolorsavailable).HasColumnName(@"displaycolorsavailable").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
