// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    public interface IShoppingCartContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Class> Classes { get; set; } // Classes
        System.Data.Entity.DbSet<Customer> Customers { get; set; } // Customers
        System.Data.Entity.DbSet<Department> Departments { get; set; } // Departments
        System.Data.Entity.DbSet<Manufacturer> Manufacturers { get; set; } // Manufacturers
        System.Data.Entity.DbSet<Product> Products { get; set; } // Products
        System.Data.Entity.DbSet<Receipt> Receipts { get; set; } // Receipts
        System.Data.Entity.DbSet<ReceiptLine> ReceiptLines { get; set; } // ReceiptLine
        System.Data.Entity.DbSet<ShipAddress> ShipAddresses { get; set; } // ShipAddresses
        System.Data.Entity.DbSet<ShipMethod> ShipMethods { get; set; } // ShipMethods
        System.Data.Entity.DbSet<Shiprate> Shiprates { get; set; } // shiprates
        System.Data.Entity.DbSet<ShoppingCartHeader> ShoppingCartHeaders { get; set; } // ShoppingCartHeader
        System.Data.Entity.DbSet<ShoppingCartLine> ShoppingCartLines { get; set; } // ShoppingCartLine
        System.Data.Entity.DbSet<Sku> Skus { get; set; } // Skus
        System.Data.Entity.DbSet<State> States { get; set; } // States
        System.Data.Entity.DbSet<SubClass> SubClasses { get; set; } // SubClasses
        System.Data.Entity.DbSet<Tax> Taxes { get; set; } // Taxes
        System.Data.Entity.DbSet<Taxrate> Taxrates { get; set; } // Taxrates

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
       // System.Data.Entity.DbSet Set(System.Type entityType);
       // System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
