// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // Manufacturers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class Manufacturer
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // name (length: 35)

        // Reverse navigation

        /// <summary>
        /// Child Products where [Products].[manufacturerId] point to this entity (FK_Manufacturer_ToProduct)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Products.FK_Manufacturer_ToProduct

        public Manufacturer()
        {
            Name = "";
            Products = new System.Collections.Generic.List<Product>();
        }
    }

}
// </auto-generated>
