// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // ReceiptLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class ReceiptLine
    {
        public int Id { get; set; } // Id (Primary key)
        public int Receiptid { get; set; } // receiptid
        public decimal Cost { get; set; } // cost
        public int? Department { get; set; } // department
        public string Description { get; set; } // description (length: 65)
        public decimal? Gstamount { get; set; } // gstamount
        public decimal? Pstamount { get; set; } // pstamount
        public int Qty { get; set; } // qty
        public decimal? Retailprice { get; set; } // retailprice
        public decimal Sellingprice { get; set; } // sellingprice
        public System.DateTime? Expectedship { get; set; } // expectedship
        public int? Shipqty { get; set; } // shipqty
        public int Sku { get; set; } // sku
        public string Color { get; set; } // color (length: 5)
        public string Size { get; set; } // size (length: 15)
        public string Subsize { get; set; } // subsize (length: 15)
        public decimal Shippingbasetax { get; set; } // shippingbasetax
        public decimal Shippingpremiumtax { get; set; } // shippingpremiumtax
        public decimal Shippingtaxamount { get; set; } // shippingtaxamount
        public decimal Taxamount { get; set; } // taxamount
        public int Taxtableid { get; set; } // taxtableid
        public string Trackingno { get; set; } // trackingno (length: 30)
        public string Flags { get; set; } // flags (length: 15)
        public string PersInfo { get; set; } // pers_info (length: 254)
        public int? Parentlineno { get; set; } // parentlineno
        public System.DateTime? Shipdate { get; set; } // shipdate
        public int Productid { get; set; } // productid
        public System.DateTime? Dts { get; set; } // dts
        public decimal Discount { get; set; } // discount
        public int? SplitParentLineNo { get; set; } // splitParentLineNo
        public string LineType { get; set; } // line_type (length: 1)
        public int KitParentline { get; set; } // kit_parentline

        // Foreign keys

        /// <summary>
        /// Parent Department pointed by [ReceiptLine].([Department]) (FK_Department_ToReceiptLine)
        /// </summary>
        public virtual Department Department_Department { get; set; } // FK_Department_ToReceiptLine

        /// <summary>
        /// Parent Product pointed by [ReceiptLine].([Productid]) (FK_Product_ToReceiptLine)
        /// </summary>
        public virtual Product Product { get; set; } // FK_Product_ToReceiptLine

        /// <summary>
        /// Parent Receipt pointed by [ReceiptLine].([Receiptid]) (FK_Receipt_ToReceiptLine)
        /// </summary>
        public virtual Receipt Receipt { get; set; } // FK_Receipt_ToReceiptLine

        public ReceiptLine()
        {
            Cost = 0.00m;
            Description = "";
            Gstamount = 0.0000m;
            Pstamount = 0.0000m;
            Qty = 0;
            Retailprice = 0.00m;
            Sellingprice = 0.00m;
            Shipqty = 0;
            Color = "";
            Size = "";
            Subsize = "";
            Shippingbasetax = 0.0000m;
            Shippingpremiumtax = 0.0000m;
            Shippingtaxamount = 0.0000m;
            Taxamount = 0.0000m;
            Taxtableid = 0;
            Trackingno = "";
            Flags = "";
            PersInfo = "";
            Parentlineno = 0;
            Discount = 0.00m;
            LineType = "N";
            KitParentline = 0;
        }
    }

}
// </auto-generated>
