// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // ShipAddresses
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class ShipAddress
    {
        public int Id { get; set; } // Id (Primary key)
        public int Customerid { get; set; } // customerid
        public string Firstname { get; set; } // firstname (length: 35)
        public string Lastname { get; set; } // lastname (length: 35)
        public string Companyname { get; set; } // companyname (length: 50)
        public string Address1 { get; set; } // address_1 (length: 50)
        public string Address2 { get; set; } // address_2 (length: 50)
        public string City { get; set; } // city (length: 35)
        public int? State { get; set; } // state
        public string Zipcode { get; set; } // zipcode (length: 10)
        public System.DateTime? Dts { get; set; } // dts
        public string Phone { get; set; } // phone (length: 20)

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [ShipAddresses].([Customerid]) (FK_Customer_ToShipAddress)
        /// </summary>
        public virtual Customer Customer { get; set; } // FK_Customer_ToShipAddress

        /// <summary>
        /// Parent State pointed by [ShipAddresses].([State]) (FK_State_ToShipAddress)
        /// </summary>
        public virtual State State_State { get; set; } // FK_State_ToShipAddress

        public ShipAddress()
        {
            Firstname = "";
            Lastname = "";
            Address1 = "";
            City = "";
            Zipcode = "";
            Phone = "";
        }
    }

}
// </auto-generated>
