// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // shiprates
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class Shiprate
    {
        public int Id { get; set; } // Id (Primary key)
        public int ShipMethodId { get; set; } // ShipMethodId (Primary key)
        public decimal Amount { get; set; } // Amount (Primary key)
        public decimal StartAmount { get; set; } // StartAmount (Primary key)
        public decimal EndAmount { get; set; } // EndAmount (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent ShipMethod pointed by [shiprates].([ShipMethodId]) (FK_ShipMethod_ToShipRates)
        /// </summary>
        public virtual ShipMethod ShipMethod { get; set; } // FK_ShipMethod_ToShipRates
    }

}
// </auto-generated>
