// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // ShipAddresses
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class ShipAddressConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ShipAddress>
    {
        public ShipAddressConfiguration()
            : this("dbo")
        {
        }

        public ShipAddressConfiguration(string schema)
        {
            ToTable("ShipAddresses", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Customerid).HasColumnName(@"customerid").HasColumnType("int").IsRequired();
            Property(x => x.Firstname).HasColumnName(@"firstname").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(35);
            Property(x => x.Lastname).HasColumnName(@"lastname").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(35);
            Property(x => x.Companyname).HasColumnName(@"companyname").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Address1).HasColumnName(@"address_1").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Address2).HasColumnName(@"address_2").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(50);
            Property(x => x.City).HasColumnName(@"city").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(35);
            Property(x => x.State).HasColumnName(@"state").HasColumnType("int").IsOptional();
            Property(x => x.Zipcode).HasColumnName(@"zipcode").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(10);
            Property(x => x.Dts).HasColumnName(@"dts").HasColumnType("datetime").IsOptional();
            Property(x => x.Phone).HasColumnName(@"phone").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(20);

            // Foreign keys
            HasOptional(a => a.State_State).WithMany(b => b.ShipAddresses).HasForeignKey(c => c.State).WillCascadeOnDelete(false); // FK_State_ToShipAddress
            HasRequired(a => a.Customer).WithMany(b => b.ShipAddresses).HasForeignKey(c => c.Customerid).WillCascadeOnDelete(false); // FK_Customer_ToShipAddress
        }
    }

}
// </auto-generated>
