// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // ShipMethods
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class ShipMethod
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // name (length: 75)
        public string Providerinfo { get; set; } // providerinfo (length: 25)
        public int? Sortorder { get; set; } // sortorder

        // Reverse navigation

        /// <summary>
        /// Child Receipts where [Receipts].[shipmethodid] point to this entity (FK_ShipMethod_ToReceipt)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Receipt> Receipts { get; set; } // Receipts.FK_ShipMethod_ToReceipt
        /// <summary>
        /// Child Shiprates where [shiprates].[ShipMethodId] point to this entity (FK_ShipMethod_ToShipRates)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Shiprate> Shiprates { get; set; } // shiprates.FK_ShipMethod_ToShipRates

        public ShipMethod()
        {
            Name = "";
            Providerinfo = "";
            Receipts = new System.Collections.Generic.List<Receipt>();
            Shiprates = new System.Collections.Generic.List<Shiprate>();
        }
    }

}
// </auto-generated>
