// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // ShoppingCartHeader
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class ShoppingCartHeader
    {
        public int Id { get; set; } // Id (Primary key)
        public string GiftRegId { get; set; } // GiftRegID (length: 16)
        public string OrderNotes { get; set; } // OrderNotes (length: 2147483647)
        public System.DateTime? Timestamp { get; set; } // timestamp
        public string SessionId { get; set; } // SessionId (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child ShoppingCartLines where [ShoppingCartLine].[CartID] point to this entity (FK_ShoppingCartHeader_ToPShoppingCartLine)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ShoppingCartLine> ShoppingCartLines { get; set; } // ShoppingCartLine.FK_ShoppingCartHeader_ToPShoppingCartLine

        public ShoppingCartHeader()
        {
            ShoppingCartLines = new System.Collections.Generic.List<ShoppingCartLine>();
        }
    }

}
// </auto-generated>
