// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // ShoppingCartHeader
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class ShoppingCartHeaderConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ShoppingCartHeader>
    {
        public ShoppingCartHeaderConfiguration()
            : this("dbo")
        {
        }

        public ShoppingCartHeaderConfiguration(string schema)
        {
            ToTable("ShoppingCartHeader", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GiftRegId).HasColumnName(@"GiftRegID").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(16);
            Property(x => x.OrderNotes).HasColumnName(@"OrderNotes").HasColumnType("text").IsOptional().IsUnicode(false).HasMaxLength(2147483647);
            Property(x => x.Timestamp).HasColumnName(@"timestamp").HasColumnType("datetime").IsOptional();
            Property(x => x.SessionId).HasColumnName(@"SessionId").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

}
// </auto-generated>
