// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // States
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class State
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // name (length: 50)
        public string Providerinfo { get; set; } // providerinfo (length: 25)
        public int Taxid { get; set; } // taxid
        public int? TaxableShipping { get; set; } // taxableShipping
        public string Code { get; set; } // Code (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Customers where [Customers].[state] point to this entity (FK_State_ToCustomer)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Customer> Customers { get; set; } // Customers.FK_State_ToCustomer
        /// <summary>
        /// Child ShipAddresses where [ShipAddresses].[state] point to this entity (FK_State_ToShipAddress)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ShipAddress> ShipAddresses { get; set; } // ShipAddresses.FK_State_ToShipAddress

        public State()
        {
            Name = "";
            Providerinfo = "";
            Taxid = 0;
            TaxableShipping = 0;
            Customers = new System.Collections.Generic.List<Customer>();
            ShipAddresses = new System.Collections.Generic.List<ShipAddress>();
        }
    }

}
// </auto-generated>
