// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // SubClasses
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class SubClass
    {
        public int Id { get; set; } // Id (Primary key)
        public int DepartmentId { get; set; } // departmentId
        public int ClassId { get; set; } // classId
        public string Name { get; set; } // name (length: 40)
        public int? Web { get; set; } // web
        public string Description { get; set; } // description (length: 2147483647)
        public string Pictureext { get; set; } // pictureext (length: 3)

        // Reverse navigation

        /// <summary>
        /// Child Products where [Products].[subclassId] point to this entity (FK_SubClass_ToProduct)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Products.FK_SubClass_ToProduct

        // Foreign keys

        /// <summary>
        /// Parent Class pointed by [SubClasses].([ClassId]) (FK_Class_ToSubClass)
        /// </summary>
        public virtual Class Class { get; set; } // FK_Class_ToSubClass

        /// <summary>
        /// Parent Department pointed by [SubClasses].([DepartmentId]) (FK_Departments_ToSubClass)
        /// </summary>
        public virtual Department Department { get; set; } // FK_Departments_ToSubClass

        public SubClass()
        {
            Products = new System.Collections.Generic.List<Product>();
        }
    }

}
// </auto-generated>
