// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // Taxes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class Tax
    {
        public int Id { get; set; } // Id (Primary key)
        public string Taxtype { get; set; } // taxtype (length: 1)
        public string Name { get; set; } // name (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child Taxrates where [Taxrates].[taxid] point to this entity (FK_Tax_ToTaxrate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Taxrate> Taxrates { get; set; } // Taxrates.FK_Tax_ToTaxrate

        public Tax()
        {
            Taxtype = "";
            Name = "";
            Taxrates = new System.Collections.Generic.List<Taxrate>();
        }
    }

}
// </auto-generated>
