// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ShoppingCart.Data
{

    // Taxrates
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.3.0")]
    public class TaxrateConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Taxrate>
    {
        public TaxrateConfiguration()
            : this("dbo")
        {
        }

        public TaxrateConfiguration(string schema)
        {
            ToTable("Taxrates", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Taxid).HasColumnName(@"taxid").HasColumnType("int").IsRequired();
            Property(x => x.Rate).HasColumnName(@"rate").HasColumnType("decimal").IsRequired().HasPrecision(8,4);
            Property(x => x.StartAmount).HasColumnName(@"start_amount").HasColumnType("decimal").IsRequired().HasPrecision(12,2);
            Property(x => x.EndAmount).HasColumnName(@"end_amount").HasColumnType("decimal").IsRequired().HasPrecision(12,2);
            Property(x => x.Ratetype).HasColumnName(@"ratetype").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1);

            // Foreign keys
            HasRequired(a => a.Tax).WithMany(b => b.Taxrates).HasForeignKey(c => c.Taxid).WillCascadeOnDelete(false); // FK_Tax_ToTaxrate
        }
    }

}
// </auto-generated>
