CREATE TABLE [dbo].[Departments]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [name] nvarchar(50)   NULL,
  [web] INT DEFAULT NULL,
  [checkstock] INT DEFAULT NULL,
  [stockstatusid] nvarchar(5)   NULL,
  [description] text ,
  [pictureext] char(3)   NULL,
  [browsestyle] INT DEFAULT NULL,
  [classlisting] INT DEFAULT NULL,
  [numproducts] INT DEFAULT NULL,
  [numproductsperrow] INT DEFAULT NULL,
  [showmanufacturer] INT DEFAULT NULL,
  [coloralias] nvarchar(25)   NULL,
  [sizealias] nvarchar(25)   NULL,
  [subsizealias] nvarchar(25)   NULL,
  [tnheight] int DEFAULT NULL,
  [tnwidth] int DEFAULT NULL,
  [fabricalias] nvarchar(25)   NULL,
  [dept_title_tag] nvarchar(150)   NULL,
  [flags] nvarchar(15)   NULL,
  [pers_code] nvarchar(15)   NULL,
  [dontshowdefprodpic] INT DEFAULT '0',
  [pagesbeforeafter] INT DEFAULT NULL,
  [paginationbottom] INT DEFAULT '0',
  [paginationtop] INT DEFAULT '0',
  [pricelabel] nvarchar(30)   NULL,
  [compare_at_label] nvarchar(30)   NULL,
  [sale_regprice_label] nvarchar(30)   NULL,
  [saleprice_label] nvarchar(30)   NULL,
  [stockstatus_label] nvarchar(30)   NULL,
  [browsesortstyle] INT NOT NULL DEFAULT '0',
  [modelidalias] nvarchar(25)   NULL,
  [productdetailstyle] int DEFAULT '0',
  [default_weight] decimal(15,2) NOT NULL DEFAULT '1.00',
  [manufactureralias] nvarchar(25)   NULL,
  [showfabric] INT DEFAULT '0',
  [relateditemsalias] nvarchar(75)   NULL,
  [relateditemsnumperrow] int DEFAULT '3',
  [displaydepartmentimage] INT DEFAULT '0',
  [displaycolorsavailable] INT DEFAULT '0' 
)
