CREATE TABLE [dbo].[ReceiptLine]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [receiptid] INT NOT NULL DEFAULT '',
  [cost] decimal(12,2) NOT NULL DEFAULT '0.00',
  [department] INT DEFAULT '',
  [description] nvarchar(65) NOT NULL DEFAULT '',
  [gstamount] decimal(15,4) DEFAULT '0.0000',
  [pstamount] decimal(15,4) DEFAULT '0.0000',
  [qty] INT NOT NULL DEFAULT '0',
  [retailprice] decimal(12,2) DEFAULT '0.00',
  [sellingprice] decimal(12,2) NOT NULL DEFAULT '0.00',
  [expectedship] datetime DEFAULT '0000-00-00 00:00:00',
  [shipqty] INT DEFAULT '0',
  [sku] INT NOT NULL DEFAULT '',
  [color] nvarchar(5) DEFAULT '',
  [size] nvarchar(15) DEFAULT '',
  [subsize] nvarchar(15) DEFAULT '',
  [shippingbasetax] decimal(15,4) NOT NULL DEFAULT '0.0000',
  [shippingpremiumtax] decimal(15,4) NOT NULL DEFAULT '0.0000',
  [shippingtaxamount] decimal(15,4) NOT NULL DEFAULT '0.0000',
  [taxamount] decimal(15,4) NOT NULL DEFAULT '0.0000',
  [taxtableid] INT NOT NULL DEFAULT '0',
  [trackingno] nvarchar(30) DEFAULT '',
  [flags] nvarchar(15) NOT NULL DEFAULT '',
  [pers_info] nvarchar(254) DEFAULT '',
  [parentlineno] INT DEFAULT '0',
  [shipdate] datetime DEFAULT '0000-00-00 00:00:00',
  [productid]INT NOT NULL DEFAULT '',
  [dts] datetime DEFAULT NULL,
  [discount] decimal(15,2) NOT NULL DEFAULT '0.00',
  [splitParentLineNo] INT DEFAULT NULL,
  [line_type] char(1) NOT NULL DEFAULT 'N',
  [kit_parentline] INT NOT NULL DEFAULT '0',
  CONSTRAINT [FK_Receipt_ToReceiptLine] FOREIGN KEY ([receiptid]) REFERENCES [Receipts]([Id]),
  CONSTRAINT [FK_Department_ToReceiptLine] FOREIGN KEY ([department]) REFERENCES [departments]([Id]),
  CONSTRAINT [FK_Product_ToReceiptLine] FOREIGN KEY ([productId]) REFERENCES [products]([Id])

)
