CREATE TABLE [dbo].[Receipts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [customerid] INT NOT NULL DEFAULT '',
  [dts] datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  [gsttotal] decimal(15,4) DEFAULT '0.0000',
  [psttotal] decimal(15,4) DEFAULT '0.0000',
  [linecount] INT NOT NULL DEFAULT '0',
  [shippingbasetax] decimal(15,4) DEFAULT '0.0000',
  [shippingpremiumtax] decimal(15,4) DEFAULT '0.0000',
  [shippingtaxtotal] decimal(15,4) DEFAULT '0.0000',
  [subtotal] decimal(12,2) NOT NULL DEFAULT '0.00',
  [taxtotal] decimal(15,4) NOT NULL DEFAULT '0.0000',
  [version] nvarchar(8) NOT NULL DEFAULT '',
  [shipmethodid] INT NOT NULL DEFAULT '0',
  [shiprateid] INT NOT NULL DEFAULT '0',
  [shipname] nvarchar(75) NOT NULL DEFAULT '',
  [shipstartamount] decimal(12,2) NOT NULL DEFAULT '0.00',
  [shipendamount] decimal(12,2) NOT NULL DEFAULT '0.00',
  [paymentid] INT NOT NULL DEFAULT '0',
  [paymentname] nvarchar(35) NOT NULL DEFAULT '',
  [ccnumber] nvarchar(25) DEFAULT '',
  [expirationmonth] INT DEFAULT '0',
  [expirationyear] INT DEFAULT NULL,
  [orderflags] nvarchar(15) NOT NULL DEFAULT '',
  [customernotes] text,
  [lastactivity] datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  [cvv2] nvarchar(4) DEFAULT '',
  [shipfirstname] nvarchar(35) NOT NULL DEFAULT '',
  [shiplastname] nvarchar(35) NOT NULL DEFAULT '',
  [shipcompany] nvarchar(45) DEFAULT '',
  [shipaddress1] nvarchar(50) NOT NULL DEFAULT '',
  [shipaddress2] nvarchar(50) DEFAULT '',
  [shipcity] nvarchar(35) NOT NULL DEFAULT '',
  [shipstate] nvarchar(10) NOT NULL DEFAULT '',
  [shipzipcode] nvarchar(10) NOT NULL DEFAULT '',
  [shipphone] nvarchar(20) NOT NULL DEFAULT '',
  [grid] nvarchar(10) DEFAULT NULL,
  [shipping_base] decimal(12,2) NOT NULL DEFAULT '0.00',
  [shipping_premiums] decimal(12,2) NOT NULL DEFAULT '0.00',
  [internalNotes] text,
  [couponCode] nvarchar(15) DEFAULT NULL,
  [couponCodeId] INT DEFAULT NULL,
  [discounts] decimal(12,2) DEFAULT NULL,
  CONSTRAINT [FK_Customer_ToReceipt] FOREIGN KEY ([customerid]) REFERENCES [customers]([Id]),
  CONSTRAINT [FK_ShipMethod_ToReceipt] FOREIGN KEY ([shipmethodid]) REFERENCES [shipmethods]([Id])
)
